apiVersion: v1
kind: Service
metadata:
  namespace: default 
  labels:
    component: mysql 
  name: mysql-nodeport
spec:
  type: NodePort
  selector:
    component: mysql
  ports:
    - port: 3306 
      targetPort: 3306
      nodePort: 13306
      name: cli
