apiVersion: v1
kind: Service
metadata:
  namespace: default 
  labels:
    component: mysql 
  name: mysql
spec:
  clusterIP: 10.254.0.36
  selector:
    component: mysql
  ports:
    - port: 3306 
      targetPort: 3306
      name: cli
